# Generated by Django 5.2.8 on 2026-01-15 10:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresitesettings',
            name='about_us',
            field=wagtail.fields.RichTextField(blank=True, help_text='About us content.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='announcement_bar_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Announcement bar text.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='announcement_enabled',
            field=models.BooleanField(default=False, help_text='Toggle the announcement bar on/off.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='contact_address',
            field=wagtail.fields.RichTextField(blank=True, help_text='Contact address or location details.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='faqs',
            field=wagtail.fields.RichTextField(blank=True, help_text='Frequently asked questions content.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='privacy_policy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Privacy policy content.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='return_refund_policy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Return and refund policy content.'),
        ),
        migrations.AlterField(
            model_name='coresitesettings',
            name='terms_and_conditions',
            field=wagtail.fields.RichTextField(blank=True, help_text='Terms and conditions content.'),
        ),
    ]
