# Generated by Django 5.2.8 on 2026-01-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Short excerpt/summary for listings', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('published_date', models.DateTimeField(blank=True, help_text='Date when the post was published', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the post is published and visible')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this post has been viewed')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of the blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Featured image for the blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['is_published', 'published_date'], name='blog_blogpo_is_publ_1ca4f0_idx'), models.Index(fields=['author', 'is_published'], name='blog_blogpo_author__1424cf_idx')],
            },
        ),
    ]
