# Generated by Django 5.2.8 on 2026-01-15 10:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.fields.RichTextField(help_text='Full blog post content'),
        ),
    ]
