# Generated by Django 5.2.8 on 2026-01-03 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('courier_guy', 'The Courier Guy'), ('dhl', 'DHL'), ('pep_paxi', 'Pep Paxi'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('api_enabled', models.BooleanField(default=False, help_text='Whether to use API for rate calculation')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API configuration (API keys, endpoints, etc.)')),
                ('manual_rates', models.JSONField(blank=True, default=dict, help_text='Manual shipping rates configuration')),
                ('estimated_days_min', models.IntegerField(default=3, help_text='Minimum estimated delivery days')),
                ('estimated_days_max', models.IntegerField(default=7, help_text='Maximum estimated delivery days')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='checkout_sh_code_76d20d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('payfast', 'PayFast')], default='payfast', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payfast_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payfast_data', models.JSONField(blank=True, default=dict, help_text='PayFast callback/response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='cart.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='checkout_pa_transac_3655ee_idx'), models.Index(fields=['order', '-created_at'], name='checkout_pa_order_i_1ff367_idx'), models.Index(fields=['status', 'payment_method'], name='checkout_pa_status_eca28b_idx'), models.Index(fields=['payfast_payment_id'], name='checkout_pa_payfast_e54a95_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cart_data', models.JSONField(default=dict, help_text='Cart items and currency')),
                ('shipping_address', models.JSONField(blank=True, default=dict, null=True)),
                ('billing_address', models.JSONField(blank=True, default=dict, null=True)),
                ('shipping_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost_zar', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('discount_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount_zwl', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount_zar', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('address_collected', 'Address Collected'), ('shipping_selected', 'Shipping Selected'), ('payment_selected', 'Payment Selected'), ('order_created', 'Order Created'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='cart.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('selected_shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='checkout.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token'], name='checkout_ch_session_127186_idx'), models.Index(fields=['user', '-created_at'], name='checkout_ch_user_id_e6e24b_idx'), models.Index(fields=['status', 'expires_at'], name='checkout_ch_status_c6b680_idx')],
            },
        ),
    ]
