# Generated by Django 5.2.8 on 2026-01-10 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_update_manufacturersubmission_address_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='manufacturer',
            new_name='manufacture_slug_9791a9_idx',
            old_name='manufacturer_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='manufacturer',
            new_name='manufacture_is_acti_2d661b_idx',
            old_name='manufacturer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='manufacturer',
            new_name='manufacture_provinc_d7f10b_idx',
            old_name='manufacturer_location_idx',
        ),
        migrations.AddIndex(
            model_name='manufacturersubmission',
            index=models.Index(fields=['status'], name='manufacture_status_876491_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturersubmission',
            index=models.Index(fields=['created_at'], name='manufacture_created_e8405a_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturersubmission',
            index=models.Index(fields=['email'], name='manufacture_email_19204f_idx'),
        ),
    ]
