# Generated by Django 5.2.8 on 2025-12-28 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ready_to_buy', 'Ready to Buy'), ('collect', 'Collect'), ('enquire', 'Enquire'), ('promotional', 'Promotional')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('brand', models.CharField(help_text='Brand name (must be Zimbabwean)', max_length=200)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer name', max_length=200)),
                ('is_proudlyzimmart_brand', models.BooleanField(default=False, help_text="Product is ProudlyZimmart's own brand")),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_zwl', models.DecimalField(blank=True, decimal_places=2, help_text='Price in ZWL RTGS', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Price in ZAR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price_zwl', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price in ZWL RTGS', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price in ZAR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when stock falls below this', validators=[django.core.validators.MinValueValidator(0)])),
                ('track_stock', models.BooleanField(default=True, help_text='Track stock for this product')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_standard', models.BooleanField(default=True, help_text='Product meets standard requirements')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions (L x W x H)', max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('bundle_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Bundle price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bundle_price_zwl', models.DecimalField(blank=True, decimal_places=2, help_text='Bundle price in ZWL RTGS', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bundle_price_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Bundle price in ZAR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('savings_amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved in USD', max_digits=10, null=True)),
                ('savings_amount_zwl', models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved in ZWL RTGS', max_digits=10, null=True)),
                ('savings_amount_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved in ZAR', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Bundle image', null=True, upload_to='bundles/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_989470_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2b3301_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary product image')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['is_primary', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variation name (e.g., 'Size', 'Color', 'Model')", max_length=100)),
                ('value', models.CharField(help_text="Variation value (e.g., 'Large', 'Red', 'Model X')", max_length=100)),
                ('sku', models.CharField(blank=True, help_text='SKU for this variation', max_length=100, unique=True)),
                ('price_adjustment_usd', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment in USD (+/-)', max_digits=10)),
                ('price_adjustment_zwl', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment in ZWL RTGS (+/-)', max_digits=10)),
                ('price_adjustment_zar', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment in ZAR (+/-)', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'ordering': ['order', 'name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image (optional, will use YouTube thumbnail if not provided)', null=True, upload_to='product_videos/thumbnails/')),
                ('title', models.CharField(blank=True, help_text='Video title (optional, can be extracted from YouTube)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Video description')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct Link'), ('other', 'Other')], default='youtube', help_text='Type of video platform', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary product video')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'ordering': ['is_primary', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='products.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_products', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Review approved by admin')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Reviewer purchased this product')),
                ('helpful_count', models.IntegerField(default=0, help_text='Number of users who found this helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this product in the bundle', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='products.product')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.productbundle')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('bundle', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'name', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='relatedproduct',
            unique_together={('product', 'related_product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
