# Generated by Django 5.2.8 on 2026-01-02 09:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(help_text='Select an image from the Wagtail image library', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product'),
        ),
    ]
